// Interactive setup script to help configure Firebase
const readline = require('readline');
const fs = require('fs');
const path = require('path');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function setup() {
  console.log('\n🚀 Hospital Management System - Firebase Setup\n');
  console.log('This script will help you configure Firebase for the application.\n');
  
  console.log('📋 Prerequisites:');
  console.log('   1. A Firebase project created at https://console.firebase.google.com');
  console.log('   2. Authentication enabled (Email/Password)');
  console.log('   3. Firestore Database created\n');
  
  const hasProject = await question('Do you already have a Firebase project? (y/n): ');
  
  if (hasProject.toLowerCase() !== 'y') {
    console.log('\n📝 Please create a Firebase project first:');
    console.log('   1. Go to https://console.firebase.google.com');
    console.log('   2. Click "Add project"');
    console.log('   3. Follow the setup wizard');
    console.log('   4. Enable Authentication > Email/Password');
    console.log('   5. Create Firestore Database\n');
    
    const continueSetup = await question('Press Enter when you have created the project, or type "exit" to quit: ');
    if (continueSetup.toLowerCase() === 'exit') {
      rl.close();
      return;
    }
  }
  
  console.log('\n📝 Now let\'s get your Firebase configuration:');
  console.log('   1. Go to Firebase Console > Project Settings (gear icon)');
  console.log('   2. Scroll to "Your apps" section');
  console.log('   3. If no web app exists, click Web icon (</>) to add one');
  console.log('   4. Copy the values from firebaseConfig object\n');
  
  const apiKey = await question('Enter NEXT_PUBLIC_FIREBASE_API_KEY: ');
  const authDomain = await question('Enter NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ');
  const projectId = await question('Enter NEXT_PUBLIC_FIREBASE_PROJECT_ID: ');
  const storageBucket = await question('Enter NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ');
  const messagingSenderId = await question('Enter NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ');
  const appId = await question('Enter NEXT_PUBLIC_FIREBASE_APP_ID: ');
  
  // Create .env.local
  const envContent = `# Firebase Configuration
# Generated by interactive setup script

NEXT_PUBLIC_FIREBASE_API_KEY=${apiKey}
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${authDomain}
NEXT_PUBLIC_FIREBASE_PROJECT_ID=${projectId}
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${storageBucket}
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${messagingSenderId}
NEXT_PUBLIC_FIREBASE_APP_ID=${appId}
`;
  
  const envPath = path.join(process.cwd(), '.env.local');
  fs.writeFileSync(envPath, envContent);
  console.log('\n✅ .env.local file created successfully!\n');
  
  // Update seed-data.ts
  const seedDataPath = path.join(process.cwd(), 'scripts', 'seed-data.ts');
  let seedDataContent = fs.readFileSync(seedDataPath, 'utf-8');
  
  seedDataContent = seedDataContent.replace(
    /apiKey: process\.env\.NEXT_PUBLIC_FIREBASE_API_KEY \|\| ".*"/,
    `apiKey: "${apiKey}"`
  );
  seedDataContent = seedDataContent.replace(
    /authDomain: process\.env\.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN \|\| ".*"/,
    `authDomain: "${authDomain}"`
  );
  seedDataContent = seedDataContent.replace(
    /projectId: process\.env\.NEXT_PUBLIC_FIREBASE_PROJECT_ID \|\| ".*"/,
    `projectId: "${projectId}"`
  );
  seedDataContent = seedDataContent.replace(
    /storageBucket: process\.env\.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET \|\| ".*"/,
    `storageBucket: "${storageBucket}"`
  );
  seedDataContent = seedDataContent.replace(
    /messagingSenderId: process\.env\.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID \|\| ".*"/,
    `messagingSenderId: "${messagingSenderId}"`
  );
  seedDataContent = seedDataContent.replace(
    /appId: process\.env\.NEXT_PUBLIC_FIREBASE_APP_ID \|\| ".*"/,
    `appId: "${appId}"`
  );
  
  fs.writeFileSync(seedDataPath, seedDataContent);
  console.log('✅ Updated scripts/seed-data.ts with your Firebase config\n');
  
  console.log('📋 Next steps:');
  console.log('   1. Login to Firebase: firebase login');
  console.log('   2. Initialize Firestore: firebase init firestore');
  console.log('      - Select your project');
  console.log('      - Use existing firestore.rules file');
  console.log('      - Use existing firestore.indexes.json file');
  console.log('   3. Deploy rules: firebase deploy --only firestore:rules');
  console.log('   4. (Optional) Seed data: npx ts-node scripts/seed-data.ts');
  console.log('   5. Start dev server: npm run dev\n');
  
  const seedNow = await question('Would you like to seed sample data now? (y/n): ');
  if (seedNow.toLowerCase() === 'y') {
    console.log('\n⚠️  Make sure you have:');
    console.log('   1. Logged in to Firebase (firebase login)');
    console.log('   2. Deployed Firestore rules');
    console.log('\nRunning seed script...\n');
    // The actual seeding will be done separately
  }
  
  rl.close();
  console.log('\n✅ Setup complete! You can now start the development server with: npm run dev\n');
}

setup().catch(console.error);



